### ISSUE TITLE
setup installs nvidia drivers v375 - incompatible with g2 instance

### ISSUE THREAD

**Issue by pigiuz** [plumbee/nvidia-hw-accelerated-box#1]
https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-367/+bug/1674930

**Comment by pgatplumbee** [comment]
@nbrochu check this out, I can run chrome on this setup with webgl

**Comment by nbrochu** [comment]
Gonna try this as soon as I get the chance. Thanks!
Feel free to close the issue if you verified it working. It's a script so no reason why I wouldn't be able to reproduce it.

**Comment by nbrochu** [comment]
Ran everything on a fresh box. 

nvidia-docker now refuses to start: `nvidia-docker-plugin[6677]: /usr/bin/nvidia-docker-plugin | 2017/04/06 20:20:27 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?`

EDIT: My server bootstrapping task was conflicting with this. Managed to fix the issue.

**Comment by nbrochu** [comment]
Next Issue: Not seeing Mate and TurboVNC come up as usual after the scripted reboot.

**Comment by nbrochu** [comment]
We are good to go! Thank you again.

<img width="644" alt="screen shot 2017-04-06 at 6 54 58 pm" src="https://cloud.githubusercontent.com/assets/35039/24778837/be759e20-1afa-11e7-84c7-839085eb39d5.png">
