### ISSUE TITLE
Resources confliction

### ISSUE THREAD

**Issue by zengzhi2015** [plumbee/nvidia-hw-accelerated-box#6]
Hi, friend! Thanks for your genius work. I can finally find a way to do 3D rendering as well as computation in the remote cloud desktop. However, it seems that the framework has a bit problem when I run ‘vglrun [program like Gazebo]’ in a command line window opened in the remote cloud desktop. Though the program runs properly, the VNC viewer consistently reports that it is trying to reconnect, which prevent me from interacting with the desktop. So, it would be very much appreciated if you could inform me about how to solve this problem. Thanks!
![dcbc98dd-cfbd-445d-b9fb-7923b82d263a](https://user-images.githubusercontent.com/15316441/47347466-e0110e80-d6e1-11e8-9b8f-3e2ea8fefd3b.png)

**Comment by pigiuz** [comment]
hey @zengzhi2015
if vnc tries to reconnect it's probably because it got disconnected :)

maybe the command you launch is turning off vnc for some reason?
did you try to launch vnc on a different port?

I found that @yrahal created a setup similar here and gazebo is actually one of the installed programs https://github.com/yrahal/ec2-setup
@yrahal any input here?

**Comment by zengzhi2015** [comment]
Hi, friend. Thanks for your reply. I have found the problem. I should not use RealVNC viewer on my Pad. Rather, I should use the PC version TurboVNC.

**Comment by pigiuz** [comment]
@zengzhi2015 thanks for following up on this, can I ask you... did you find the reason why RealVNC doesn't work? it would be good to know so we can address the root cause and make this solution even better

**Comment by zengzhi2015** [comment]
Hi, I cannot tell why this was happened. I use RealVNC reviewer on my iPad. However, the rendering on the reviewer is problematic. The VNC were disconnected constantly. Maybe, when I run vglrun Gazebo, the Desktop and Gazebo are rendered simultaneously. The iPad version RealVNC may not be so much compatible with the TurboVNC in such a case. A consecutive catastrophe is that when I switched to the PC version of TurboVNC after the problem, though the disconnection problem disappeared, I cannot see any 3D app rendering on the desktop screen.  
![db5e3023-40e4-466b-b5c6-ad111ddd8e10](https://user-images.githubusercontent.com/15316441/47919474-6f8c9d80-deea-11e8-8141-1ceeac6ed3dc.jpeg)
The only way I could figure out is to resetup the whole environment. 
![626509b0-0294-42ef-8354-348aa9df5a92](https://user-images.githubusercontent.com/15316441/47919940-ad3df600-deeb-11e8-9f81-3e75fcf14219.jpeg)
I am not sure why this happens. I would provide more detail when I can.
